/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsDate, ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { LocationUpdateManyWithoutTripsInput } from "./LocationUpdateManyWithoutTripsInput";
import { NoteUpdateManyWithoutTripsInput } from "./NoteUpdateManyWithoutTripsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class TripUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  destination?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => LocationUpdateManyWithoutTripsInput,
  })
  @ValidateNested()
  @Type(() => LocationUpdateManyWithoutTripsInput)
  @IsOptional()
  @Field(() => LocationUpdateManyWithoutTripsInput, {
    nullable: true,
  })
  locations?: LocationUpdateManyWithoutTripsInput;

  @ApiProperty({
    required: false,
    type: () => NoteUpdateManyWithoutTripsInput,
  })
  @ValidateNested()
  @Type(() => NoteUpdateManyWithoutTripsInput)
  @IsOptional()
  @Field(() => NoteUpdateManyWithoutTripsInput, {
    nullable: true,
  })
  notes?: NoteUpdateManyWithoutTripsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { TripUpdateInput as TripUpdateInput };
